# Generated by Django 5.0.4 on 2024-05-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('min_bid_price', models.PositiveIntegerField()),
                ('max_bid_price', models.PositiveIntegerField()),
                ('file_doc', models.FileField(blank=True, null=True, upload_to='uploaded_docs/')),
            ],
        ),
    ]
