# Generated by Django 5.0.6 on 2024-05-21 16:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('min_bid_price', models.PositiveIntegerField()),
                ('max_bid_price', models.PositiveIntegerField()),
                ('file_doc', models.FileField(blank=True, null=True, upload_to='uploaded_docs/')),
                ('posted_on', models.DateField(blank=True, default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
