# Generated by Django 5.0.6 on 2024-05-22 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_webpage', '0004_rename_bid_amount_bid_amount_and_more'),
        ('post_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='post_project.project'),
        ),
        migrations.RemoveField(
            model_name='bid',
            name='freelancer',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
